//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.01 at 10:14:52 AM PKT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://com.springbootsoap.allapis", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package allapis.springbootsoap.com;
